# jobs are unit of work each runs in its own container
# jobs containing steps that run in sequence
# workflows define order between jobs

version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: 
          name: Test required environment variables
          command: |
            set -o nounset
            echo 'Api token: $PERSONAL_API_TOKEN'
      - run:
          name: Install required tools
          command: |
            apt install curl
      - run:
          name: Where am I?
          command: |
            echo $(pws)
      - run:
          name: Test personal token
          command: |
            curl https://circleci.com/api/v1.1/me?circle-token=$PERSONAL_API_TOKEN
