# jobs are unit of work each runs in its own container
# jobs containing steps that run in sequence
# workflows define order between jobs

version: 2.1

jobs:
  build:
    docker:
      - image: byrnedo/alpine-curl
    steps:
      - checkout
      - run: 
          name: Test required environment variables
          command: |
            set -o nounset
            [ -z "$PERSONAL_API_TOKEN" ]
      - run:
          name: Set up required tools
          command: |
            apk update
            apk upgrade curl
      - run:
          name: Where am I?
          command: |
            echo $(pwd)
      - run:
          name: Test personal token
          command: |
            curl https://circleci.com/api/v1.1/me?circle-token=$PERSONAL_API_TOKEN
